services:
  patito-judge-kernel:
    build: .
    container_name: patito-judge-kernel
    restart: always
    cpuset: "2"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512m
        reservations:
          cpus: '0.5'
          memory: 256m
    labels:
      - traefik.enable=true
    user: root
    environment:
      LANG: "es_ES.UTF-8"
      HOME: "/home/judge"
      CONF: "/home/judge/etc/judge.conf"
    tty: true
    volumes:
      - ../storage:/home/judge
      - .:/mnt
    networks:
      - traefik-net
      - traefik-internal

networks:
  traefik-net:
    external: true
  traefik-internal:
    external: false
