[supervisord]
nodaemon=true
user=root

#[program:judged]
#command=/usr/bin/judged /home/judge true
#autostart=true
#autorestart=true
#startretries=3
#user=root
#environment=PATH="/usr/local/bin"
#redirect_stderr=true
#priority=999                       
#stdout_logfile=/var/log/judged.log
#stderr_logfile=/var/log/judged_err.log


[program:judged]
# Comando para iniciar el daemon. Usamos bash para establecer umask y ejecutar judged.
command=/bin/bash -c 'umask 077 && exec /usr/bin/judged'

# Directorio de trabajo
directory=/

# Autostart: inicia el programa al arrancar Supervisor
autostart=true

# Autorestart: reinicia el programa si falla
autorestart=true

# Número de segundos que Supervisor esperará antes de considerar que el programa ha fallado al iniciar
startsecs=5

# Usuario bajo el cual se ejecutará el proceso
user=judge

# Variables de entorno
environment=LANG="es_ES.UTF-8",HOME="/home/judge",CONF="/home/judge/etc/judge.conf"

# Archivos de log para stdout y stderr
stdout_logfile=/var/log/supervisor/judged_stdout.log
stderr_logfile=/var/log/supervisor/judged_stderr.log

# Redirigir stderr a stdout
redirect_stderr=true

# Señal para detener el proceso. Por defecto es SIGTERM.
# Puedes ajustar si es necesario, pero se recomienda mantener SIGTERM para una terminación ordenada.
# stopsignal=SIGTERM
